{{ ansible_managed | comment }}

FROM {{ BASEIMAGE }}{% if UPDATE_MS | bool %} as update{% endif %}

LABEL maintainer="Maxwell G <gotmax23@github>"

{% if PACKAGE_MGR_NAME == "apt" %}
ENV DEBIAN_FRONTEND=noninteractive
{% endif %}

RUN echo "**** Installing packages and updating if necessary ****" \
    && {{ PACKAGE_MGR_INSTALL_CMD }} \
        {{ all_packages | join(' ') }} \
    && echo "**** Cleaning package cache ****" \
    && {{ PACKAGE_MGR_CLEAN_CMD }} \
{% if PACKAGE_MGR_NAME == "apt" %}
    && rm -rf /var/lib/apt/lists/* \
{% endif %}
{% if MASKED_SERVICES != [] %}
    && echo "**** Masking systemd services ****" \
    && systemctl mask \
        {{ MASKED_SERVICES | join(' ') }}
{% endif %}

{% if UPDATE_MS | bool %}
FROM scratch
COPY --from=update / /
{% endif %}
CMD ["{{ DOCKER_CMD }}"]
{% if DOCKER_STOPSIGNAL is defined %}
STOPSIGNAL {{ DOCKER_STOPSIGNAL }}
{% endif %}

# {{ "vim: set filetype=dockerfile:" }}
{#
# vim: set filetype=dockerfile.jinja2:
#}
