# vim: set filetype=jinja.dockerfile:

FROM {{ BASEIMAGE }}

LABEL maintainer="Maxwell G <gotmax23@github>"

{% if PKG_MGR_NAME == "apt" %}
ENV DEBIAN_FRONTEND=noninteractive
{% endif %}

# Install systemd and python requirements and clean up
RUN {{ PKG_MGR_INSTALL_CMD }} \
    {{ ALL_PACKAGES | join(' ')}} \
{% if PKG_MGR_CLEAN_CMD is defined%}&& {{ PKG_MGR_CLEAN_CMD }} \{%endif}
&& rm -rf /usr/share/doc /usr/share/man{% if PKG_MGR == "apt" %} /var/lib/apt/lists/*{% endif %}

CMD [{{ DOCKER_CMD }}]
{% if DOCKER_STOPSIGNAL is defined %}
STOPSIGNAL {{ DOCKER_STOPSIGNAL }}
{% endif %}
