#!/usr/bin/env ansible-playbook
---
- name: Generate systemd ContainerFiles
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars_files:
    - matrix.yml

  tasks:
    - tags: [ always ]
      include_role: name="./generator"

# vim: set filetype=yaml.ansible:
