---
- hosts: localhost
  name: Generate systemd ContainerFiles
  gather_facts: false

  vars_files:
    - matrix.yml

  pre_tasks:
    - name: Remove old GH Actions workflow file
      file:
        path: "{{ repo_root }}/.github/workflows/systemd-ci.yml"
        state: absent

  roles:
    - name: gotmax23.containerfile_generator
      role: "../../generator"
