[project]
name = "systemd-containerfile-generator"
version = "0.0.0"
requires-python = ">=3.11"
classifiers = [
    "Private :: Do Not Upload",
]
dependencies = [
    "jinja2",
    "pyyaml",
]

[dependency-groups]
lint = [
    "ruff",
]
nox = [
    "nox",
]
typing = [
    "mypy",
    "types-pyyaml",
]
zizmor = [
    "zizmor",
]

[tool.uv]
package = false
