---
- name: Set DISTRO_FAMILY and GALAXY_VERSION
  set_fact:
    DISTRO_FAMILY: "{{ distro['distro_family'] }}"
    GALAXY_VERSION: "{{ output['galaxy_version'] }}"

- name: (Temporarily) Set variables in `all_vars_list` to 'EMPTY' to avoid undefined var error
  set_fact:
    "{{ item|upper }}": 'EMPTY'
  loop: "{{ all_vars_list }}"

- name: Define variables in `all_vars_list` based on hierarchy
  set_fact:
    "{{ item|upper }}": "{{ output['vars'][item] | default(distro['vars'][item] | default(distro_families[DISTRO_FAMILY]['vars'][item] | default(defaults['vars'][item]))) }}"
  loop: "{{ all_vars_list }}"

- name: Reload vars
  include_vars:
    file: "{{ matrix_file }}"

- name: Create ContainerFiles
  template:
    src: "{{ repo_root }}/{{ CF_template_src_path }}"
    dest: "{{ repo_root }}/{{ CF_output_path }}"
  when:
    - generate_ci_only is not defined or not generate_ci_only | bool

- name: Generate CI files
  template:
    src: "{{ repo_root }}/{{ CI_template_src_path }}"
    dest: "{{ repo_root }}/{{ CI_output_path }}"
