---
- name: Create necessary directories
  tags: [ always ]
  file:
    path: "{{ repo_root }}/{{ CF_output_dir }}"
    state: directory

- name: Loop over outputs
  tags: [ always ]
  include_tasks:
    file: output.yml
  loop: "{{ distro['outputs'] }}"
  loop_control:
    loop_var: output
    index_var: output_index
