FROM registry.fedoraproject.org/fedora:latest

RUN set -euo pipefail ;\
    dnf install -y \
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    ;\
    dnf install --enablerepo=updates-testing --setopt=install_weak_deps=0 -y yt-dlp ffmpeg ;\
    dnf clean all

ENTRYPOINT ["yt-dlp"]
CMD ["--help"]
