FROM quay.io/gotmax23/archlinux-systemd:any
LABEL maintainer="Maxwell G <gotmax23@github>"

#COPY mirrorlist /etc/pacman.d/mirrorlist

RUN echo "**** Installing packages and updating if necessary ****" \
    && pacman -S --needed --noconfirm \
        ansible-core base-devel git bash-completion bat vim pacman-contrib \
\
    && echo "Creating aur_builder user" \
    && useradd -m -u 1000 -G wheel -s /bin/bash aur_builder \
\
    && echo "Setting aur_builder sudoers config" \
    && echo "aur_builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/aur_builder \
\
    && echo "Validating aur_builder sudoers config" \
    && visudo -cf /etc/sudoers.d/aur_builder \
\
    && echo "**** Building and installing paru ****" \
    && sudo -u aur_builder sh -c "\
        git clone https://aur.archlinux.org/paru-bin.git /tmp/paru-bin \
        && cd /tmp/paru-bin \
        && PKGEXT='.pkg.tar' makepkg --install --syncdeps --rmdeps --noconfirm" \
\
    && echo "**** Installing ansible-collection-community-general ****" \
    && sudo -u aur_builder sh -c "\
        git clone https://aur.archlinux.org/ansible-collection-community-general.git /tmp/ansible-collection-community-general \
        && cd /tmp/ansible-collection-community-general \
        && PKGEXT='.pkg.tar' makepkg --install --syncdeps --rmdeps --noconfirm" \
\
    && echo "**** Cloning dotfiles repository and running Ansible playbook ****" \
    && sudo -u aur_builder sh -c "\
        mkdir -p ~/.ansible/roles \
        && git clone https://github.com/gotmax23/ansible-role-dotfiles ~/.ansible/roles/gotmax23.dotfiles \
        && git clone https://github.com/gotmax23/dotfiles.git /tmp/dotfiles \
        && ansible-playbook -i 'localhost,' -c local /tmp/dotfiles/dotfiles.yml" \
\
    && echo "**** Cleaning package cache and temp files ****" \
    && rm -rf /tmp/* /home/aur_builder/.cache /home/aur_builder/.cargo \
    && pacman -Scc --noconfirm \
\
    && echo "**** Setting aur_builder shell to zsh ****" \
    && chsh -s /bin/zsh aur_builder \
\
    && echo "**** Downloading Zsh plugins ****" \
    && sudo -u aur_builder zsh -ic exit \
\
    && echo "**** Unmask systemd-logind" \
    && systemctl unmask systemd-logind

ENV TERM=xterm-256color
# vim: set filetype=dockerfile:
