---
name: Checks

'on':
  pull_request:
    paths:
      - ".github/**"
      - "Containerfiles/systemd/**"
      - "src/systemd/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "Containerfiles/systemd/**"
      - "src/systemd/**"

permissions:
  contents: read

jobs:
  checks:
    name: Generator and workflow checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - name: Install session deps
        working-directory: src/systemd
        run: |
          echo -e '#!/bin/sh\n exec uv run --locked --group nox nox --force-color "$@"' > ./nox
          chmod a+x nox
          ./nox --install-only
      - name: Run zizmor in online mode
        env:
          # zizmor requirs token for some checks
          ZIZMOR_GITHUB_TOKEN: "${{ github.token }}"
        working-directory: src/systemd
        run: ./nox -R -s zizmor
      - name: Get session names
        working-directory: src/systemd
        run: ./nox -l --json | jq -r '.[].session' | grep -v zizmor > nox-sessions
      - name: Run sessions
        working-directory: src/systemd
        run: ./nox -R -s $(cat nox-sessions)
