---
name: "systemd-Fedora.36: Build and push container images"
'on':
  push:
    branches:
      - main
    paths:
      - "Containerfiles/systemd/Fedora/Fedora.36.Containerfile"
      - ".github/workflows/systemd-Fedora.36-ci.yml"
  schedule:
    - cron: "10 1 * * 0"
  workflow_dispatch:

jobs:
  build_push:
    name: Build and Push container images to quay.io
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Calculate Docker image tags # Based on https://gist.github.com/sagikazarmark/0119e1f3dde0d8e755fd0ee5a5ef4cdc
        id: tags
        run: |
          case $GITHUB_REF in
            refs/tags/*)  VERSION=${GITHUB_REF#refs/tags/};;
            refs/heads/*) VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g');;
            refs/pull/*)  VERSION=pr-${{ github.event.number }};;
            *)            VERSION=sha-${GITHUB_SHA::8};;
          esac
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=commit_hash::${GITHUB_SHA::8}
          echo ::set-output name=build_date::$(git show -s --format=%cI)
      # See https://bugzilla.redhat.com/show_bug.cgi?id=1988199#c3 for more information
      - name: Download Docker with patched seccomp
        run: |
          sudo systemctl stop docker containerd
          sudo apt-get remove --autoremove -y moby-engine moby-cli moby-buildx moby-containerd moby-runc
          sudo add-apt-repository -y ppa:pascallj/docker.io-clone3
          sudo apt-get install -y docker.io
          mkdir ~/.docker/cli-plugins
          DOCKER_BUILDX_RELEASE=$(curl -sX GET "https://api.github.com/repos/docker/buildx/releases/latest" | jq -r .tag_name)
          wget https://github.com/docker/buildx/releases/download/"${DOCKER_BUILDX_RELEASE}"/buildx-"${DOCKER_BUILDX_RELEASE}".linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
      - uses: docker/setup-qemu-action@v1
      - name: Create Buildx builder with updated image
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./Containerfiles/systemd/Fedora
          file: ./Containerfiles/systemd/Fedora/Fedora.36.Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          labels: |
            org.opencontainers.image.tite="Fedora image with systemd"
            org.opencontainers.image.description="Fedora image with systemd for Ansible testing using Podman and Molecule"
            org.opencontainers.image.url=${{ github.event.repository.html_url }}/tree/main/Containerfiles/systemd
            org.opencontainers.image.documentation=${{ github.event.repository.html_url }}/tree/main/Containerfiles/systemd/README.md
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ steps.tags.outputs.version }}
            org.opencontainers.image.created=${{ steps.tags.outputs.build_date }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
          tags: |
            quay.io/gotmax23/fedora-systemd:36
            quay.io/gotmax23/fedora-systemd:rawhide
