---
name: "systemd-Ubuntu.focal: Build and push container images"
'on':
  push:
    branches:
      - main
    paths:
      - "Containerfiles/systemd/Ubuntu/Ubuntu.focal.Containerfile"
      - ".github/workflows/systemd-Ubuntu.focal-ci.yml"
  schedule:
    - cron: "10 1 * * 0"
  workflow_dispatch:

jobs:
  build_push:
    name: Build and Push container images to quay.io
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io

          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./Containerfiles/systemd/Ubuntu
          file: ./Containerfiles/systemd/Ubuntu/Ubuntu.focal.Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/gotmax23/ubuntu-systemd:focal
            quay.io/gotmax23/ubuntu-systemd:latest
            quay.io/gotmax23/ubuntu-systemd:20
            quay.io/gotmax23/ubuntu-systemd:20.04
# vim: set filetype=jinja.yaml:
