---
name: "systemd-Debian.bullseye: Build and push container images"
'on':
  push:
    branches:
      - main
    paths:
      - ./ContainerFiles/systemd/Debian/Debian.bullseye.ContainerFile
      - ./.github/workflows/systemd-Debian.bullseye-ci.yml
  schedule:
    - cron: "10 1 * * 0"

jobs:
  build_push:
    name: Build and Push container images to quay.io
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io

          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./ContainerFiles/systemd/Debian
          file: ./ContainerFiles/systemd/Debian/Debian.bullseye.ContainerFile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/gotmax23/debian-systemd:bullseye
            quay.io/gotmax23/debian-systemd:testing
# vim: set filetype=jinja.yaml:
