---
name: "yt-dlp"

'on':
  pull_request:
    paths:
      - "Containerfiles/yt-dlp/Containerfile"
      - ".github/workflows/yt-dlp.yml"
      - ".github/workflows/reusable-container-build.yml"
  push:
    branches:
      - main
    paths:
      - "Containerfiles/yt-dlp/Containerfile"
      - ".github/workflows/yt-dlp.yml"
      - ".github/workflows/reusable-container-build.yml"
  schedule:
    - cron: "10 1 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_push:
    name: Build and Push container images to quay.io
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-container-build.yml
    with:
      context: "./Containerfiles/yt-dlp"
      containerfile: "./Containerfiles/yt-dlp/Containerfile"
      platforms: "linux/amd64,linux/arm64"
      image_title: "Fedora Linux image with yt-dlp"
      image_description: "Fedora Linux image with yt-dlp"
      project_path: "Containerfiles/yt-dlp"
      documentation_path: "Containerfiles/yt-dlp/README.md"
      tags: "quay.io/gotmax23/yt-dlp"
    secrets:
      registry_username: ${{ secrets.QUAY_USERNAME }}
      registry_password: ${{ secrets.QUAY_PASSWORD }}
